### ISSUE TITLE
COLL

### ISSUE THREAD

**Issue by matthewdavis2985** [matthewdavis2985/Oyster-Data-Checks#38]
Need to create and adjust COLL script to apply to data in dbo schema. See SRVY as an example

**Comment by matthewdavis2985** [comment]
Checking Condition Index and Dermo should both be done in this script. 

Shell Pest should NOT be done in this script. I think it would be better to include ShellPest checks with the upload script since that data lags far behind (2 yrs behind in AB right now). Also be better to identify those issues during upload.

The real question is should Repro checks be included in this script? Repro data also lags behind (nearing 1 year behind in AB right now). However, it is also entered via ODIN and not direct upload. Currently, Trips aren't finished in ODIN until the Repro data is entered, so I now lean towards including Repo checks in this script. It would also reduce the number of scripts to run and maintain.

@E-Levine your input?

**Comment by E-Levine** [comment]
As you mentioned, data is not considered "Proofed" until Repro is also entered and proofed. Based on this, I think including Repro in Dermo data checks is a good idea. Since CI is not dependent on Repro, should CI and Dermo have separate scripts though?

**Comment by matthewdavis2985** [comment]
I don't think CI and Dermo should have separate scripts. They aren't _necessarily_ related, but in AB they always are related through the SampleEvent. When we do collections we always collect for both Dermo and CI. I think running all the checks (SampleEvent, WQ, CI, Dermo, and Repro) at the same time makes sense. 

One thing we'll have to look out for is childless records, which will be allowed. For example, you get to a station, take WQ, but can't find any oysters. That's still a valid SampleEvent, but won't have any CI/Dermo/Repro data connected to it. It's something that still  needs a comment, but isn't a critical Database Error.

Also, there's not a ton of fields that can be blank or have out of range values with Dermo/Repro so adding them won't take up much space or result in many errors.

**Comment by E-Levine** [comment]
That makes sense. We typically collect dermo without CI and occasionally have collected CI without dermo so we'll just modify the code as needed for the St Pete samples.
