### ISSUE TITLE
SQL stored procedures

### ISSUE THREAD

**Issue by matthewdavis2985** [matthewdavis2985/Oyster-Data-Checks#57]
Had some issues running the SQL code at the end of RCRT_hsdb. The problem being that the whole thing was not running as a single batch, thus the temp table #ValidTrips was getting dropped part way through. 

The simplest fix is to save the query at the end as a Stored Procedure. I tested it and it works on the hsdb code AND the dbo code (without having to name every column!).

My plan is to add the code to CREATE the stored procedures we need. These should be able to be used by everyone, so no need for lab specific SP's.

The output at the end will then be something like:
`EXECUTE dbo.spChecksRecruitment
	@CheckStart = '2023-01-01',
	@CheckEnd = '2023-06-30',
	@EstuaryCode = 'AB',
	@DataManager = 'Matt';`
which should be easier to run in any case. It'll also cut down on potential copy/paste errors and make for a shorter printout.

I have two questions for @berlynna 

1. Can I create stored procedures on fwcsqlint? I assume that I can, but I haven't tried
2. Do you have a specific naming convention you want me to follow for naming these procedures?
For hsdb data, I was going to use {hsdb}.{sp}{Checks}TripType ex. hsdb.spChecksRecruitment
For dbo data, I was going to use {dbo}.{sp}{Checks}TripType ex. dbo.spChecksShellBudget

@E-Levine do you see any issues or have any thoughts?

**Comment by berlynna** [comment]
@matthewdavis2985 1. Yes, you can create a stored procedure. We have to set the permissions for it (like we do when we create a new table) but that is the only thing to keep in mind. 
2. That is a good name convention. The ones that need to connect to powerapps end in flow. but since these don't this works well! I think moving the data checks into stored procedures is a good idea in general

**Comment by matthewdavis2985** [comment]
Thanks Berlynna. I've tested them locally without issue. They are deployed. Going to merge the branch back to main.
